[package]
name = "pdf-compressor-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
pdf-compressor-lib = { path = "../lib" }

[[bin]]
name = "pdfcompressor"
path = "./main.rs"

