[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
pdf-compressor = { path = "../lib" }

[profile.release]
lto = true

[[bin]]
name = "cli"
path = "./main.rs"

